query getProductById($identifier: ProductUniqueIdentifier) {
  product(identifier: $identifier) @context(provider: "vtex.search-graphql") {
    items {
      sellers {
        commertialOffer {
          AvailableQuantity
          Price
          ListPrice
          spotPrice
        }
      }
    }
  }
}
