query getProductById($identifier: ProductUniqueIdentifier)
@context(provider: "vtex.search-graphql") {
  product(identifier: $identifier) {
    
    items {
      sellers {
        commertialOffer {
          AvailableQuantity
          Price
          ListPrice
          spotPrice
        }
      }
    }
  }
}
